CREATE TABLE users (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	nickname VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	profile VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);



CREATE TABLE contents (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	user_id INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	total_page INT DEFAULT 1 NOT NULL,
	current_page INT DEFAULT 1 NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	note TEXT,
	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);