CREATE TABLE Users (
	user_id SERIAL PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);



CREATE TABLE Contents (
	content_id SERIAL PRIMARY KEY,
	users_id INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	total_pages INT NOT NULL,
	current_page INT NOT NULL,
	status VARCHAR(20),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	note TEXT
);