name: Frontend Code Quality

on:
  push:
  pull_request:

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4
      - name: Run Biome
        run: biome lint apps/dokuha-roadmap-frontend
